add function Get-CMKAllServices
Stachelritter/CheckMK-PowerShell pull request #1
Opened 2024-02-23 12:06 UTC by dOn-MoP

Hallo Fabian,
danke für die tolle Arbeit, ich kann das Modul mit minimalen Anpassungen gut nutzen.
Hier eine erste Version, um alle services aus CheckMK abzufragen, filterbar per regular expression auf die service description. 
Ein Beispiel ist als comment based help hinterlegt.
Achtung: ohne filter kommen sehr viele Daten zurück.

2024-02-23 13:17 UTC, Stachelritter commented
Danke für deinen Beitrag, ich schaue mir ihn in der kommenden Woche an.

2024-03-05 08:54 UTC, Stachelritter requested changes
Hallo, 
ich möchte vorschlagen die Funktion etwas anders zu benennen und das Verhalten anzupassen, damit es mehr in das PowerShell-Schema passt. 
- Funktionname im Singular: Get-CMKService
- Weiterer Parameter zur Einschränkung auf einzelne Hosts: HostName

Hier mein Vorschlag:
[Get-CMKService.txt](https://github.com/Stachelritter/CheckMK-PowerShell/files/14492751/Get-CMKService.txt)
Den Vorschlag würde ich so übernehmen wollen, er unterscheidet sich im Verhalten nicht zu deinem Code, bietet nur mehr Filtermöglichkeiten (und trägt einen anderen Funktionsnamen).

Viele Grüße
Fabian

2024-03-05 12:33 UTC, dOn-MoP commented
Aus meiner Sicht OK. Dann passt es zur Art und Weise wie z.B. auch Get-CMKHost funktioniert.
Auf der anderen Seite kann es auch Sinn machen, die Funktionen allgemein getrennt, also als eigenständige Funktionen bereitzustellen, so wie es in der REST-API auch eigenständige Aufrufe mit möglicherweise unterschiedlichen Rückgabeobjekten sind.

2024-03-05 12:57 UTC, Stachelritter approved these changes

2024-03-05 12:57 UTC, merged